import type { ThemeState } from "../state/types";

export const THEME_PRESETS: Record<string, ThemeState> = {
  "default-dark": {
    ui: {
      bg: "#0d0d0d",
      panel: "#171717",
      card: "#212121",
      border: "#303030",
      text: "#ececec",
      muted: "#b4b4b4",
      soft: "#676767",
      black: "#000000",
      white: "#ffffff",
      primary: "#3d3d3d",
      primaryText: "#ffffff",
    },
    groups: {
      "2007": { bg: "#4b5563" },
      "2008": { bg: "#6b7280" },
      "2009": { bg: "#9ca3af" },
      Herren: { bg: "#ffffff" },
      TBD: { bg: "#4b5563" },
    },
    locations: {
      home: "",
      bsh: "",
      shp: "",
      seminarraum: "",
      custom: {},
      definitions: {
        BSH: { abbr: "BSH", name: "BSH" },
        SHP: { abbr: "SHP", name: "SHP" },
        Seminarraum: { abbr: "Seminarraum", name: "Seminarraum" },
      },
    },
    clubName: "UBC Münster",
    locale: "de",
  },
  "slate-dark": {
    ui: {
      bg: "#121212",
      panel: "#1a1a1a",
      card: "#242424",
      border: "#313131",
      text: "#ededed",
      muted: "#b5b5b5",
      soft: "#717171",
      black: "#000000",
      white: "#ffffff",
      primary: "#3f3f3f",
      primaryText: "#ffffff",
    },
    groups: {
      "2007": { bg: "#4b5563" },
      "2008": { bg: "#6b7280" },
      "2009": { bg: "#9ca3af" },
      Herren: { bg: "#ffffff" },
      TBD: { bg: "#4b5563" },
    },
    clubName: "UBC Münster",
    locale: "de",
  },
  light: {
    ui: {
      bg: "#f8fafc",
      panel: "#ffffff",
      card: "#ffffff",
      border: "#e5e7eb",
      text: "#1f1f1f",
      muted: "#6b7280",
      soft: "#374151",
      black: "#111111",
      white: "#ffffff",
    },
    groups: {
      "2007": { bg: "#9ca3af" },
      "2008": { bg: "#d1d5db" },
      "2009": { bg: "#e5e7eb" },
      Herren: { bg: "#2b2b2b" },
      TBD: { bg: "#9ca3af" },
    },
    clubName: "UBC Münster",
    locale: "de",
  },
};
